name: getYouTubePlaylist

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install yt-dlp
    - name: getYouTubePlaylist
      run: |
        yt-dlp -x --audio-format mp3 -o "mp3/%(title)s.%(ext)s" https://youtube.com/playlist?list=PLZnYpvAgGYoNKL2KQQfbR3BM8WeVq2LfD

    - name: Commits
      run: |
        git config --local user.email "ika7204@naver.com"
        git config --local user.name "ika9810"
        git add .
        git commit -m "⚙️🎶[DOWNLOAD] Download YouTubePlaylist to mp3"
    - name: Push
      uses: ad-m/github-push-action@master
      with:
         branch: 'main'
         github_token: ${{ secrets.GITHUB_TOKEN }}
